#===== ROUTING =====#

### Pages générales ###
AppCofidurBundle_homepage:
    path:  /
    methods: [GET]
    defaults: { _controller: AppCofidurBundle:Page:index }

AppCofidurBundle_about:
    path:  /about
    methods: [GET]
    defaults: { _controller: AppCofidurBundle:Page:about }

AppCofidurBundle_contact:
    path: /contact
    methods: [GET]
    defaults: { _controller: AppCofidurBundle:Page:contact }

AppCofidurBundle_admin:
    path: /admin
    methods: [GET]
    defaults: { _controller: AppCofidurBundle:Page:admin }

### Matrice de compétences ###
AppCofidurBundle_skillMatrix:
    path: /skillMatrix
    methods: [POST, GET]
    defaults: { _controller: AppCofidurBundle:SkillMatrix:skillMatrix }

AppCofidurBundle_skillMatrix:
    path: /skillMatrix/
    methods: [POST, GET]
    defaults: { _controller: AppCofidurBundle:SkillMatrix:skillMatrix }

### Pages d'authentifiation ###
AppCofidurBundle_login:
    path: /login
    methods: [GET]
    defaults : { _controller: FOSUserBundle:Security:login}

AppCofidurBundle_logout:
    path: /logout
    methods: [GET]
    defaults : { _controller: FOSUserBundle:Security:logout}

#AppCofidurBundle_register:
#    path: /register
#    defaults : { _controller: FOSUserBundle:Security:register }

#AppCofidurBundle_changePassword:
#    path: /profile/change-password
#    defaults : { _controller: FOSUserBundle:Security:change-password}


# Pages des opérateurs
AppCofidurBundle_operator_add:
    path: /operator/add
    methods: [POST,GET]
    defaults: { _controller: AppCofidurBundle:Operator:add}

AppCofidurBundle_operator_edit:
    path: /operator/edit/{idOp}
    methods: [POST,GET]
    defaults: { _controller: AppCofidurBundle:Operator:edit}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_operator_setAdmin:
    path: /operator/setAdmin/{idOp}
    methods: [GET,POST]
    defaults: { _controller: AppCofidurBundle:Operator:setAdmin}
    requirements:
        methods: POST
        id: \d+

AppCofidurBundle_operator_unsetAdmin:
    path: /operator/unsetAdmin/{idOp}
    methods: [GET,POST]
    defaults: { _controller: AppCofidurBundle:Operator:unsetAdmin}
    requirements:
        methods: POST
        id: \d+

AppCofidurBundle_operator_delete:
    path: /operator/delete/{idOp}
    methods: [DELETE,GET]
    defaults: { _controller: AppCofidurBundle:Operator:delete}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_operator_show:
    path: /operator/show/{idOp}
    methods: [GET]
    defaults: { _controller: AppCofidurBundle:Operator:show}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_operator_show_all:
    path: /operators
    methods: [GET]
    defaults: { _controller: AppCofidurBundle:Operator:showAll}

### page de formation ###
AppCofidurBundle_formation_add:
    path: /formation/add
    methods: [POST,GET]
    defaults: { _controller: AppCofidurBundle:Formation:add}

AppCofidurBundle_formation_edit:
    path:  /formation/edit/{idForm}
    methods: [POST,GET]
    defaults: { _controller: AppCofidurBundle:Formation:edit }
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_formation_delete:
    path:  /formation/delete/{idForm}
    methods: [DELETE,GET]
    defaults: { _controller: AppCofidurBundle:Formation:delete }
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_formation_show:
    path:  /formation/show/{idForm}
    methods: [GET]
    defaults: { _controller: AppCofidurBundle:Formation:show }
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_formation_show_all:
    path:  /formations
    methods: [GET]
    defaults: { _controller: AppCofidurBundle:Formation:showAll }

AppCofidurBundle_formation_getNbFormed:
    path:  /formation/getNbFormed
    methods: [GET]
    defaults: { _controller: AppCofidurBundle:Formation:getNbFormed }

### page de categorie ###
AppCofidurBundle_category_add:
    path: /category/add/{idForm}
    methods: [POST,GET]
    defaults: { _controller: AppCofidurBundle:Category:add}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_category_edit:
    path: /category/edit/{idCat}
    methods: [POST,GET]
    defaults: { _controller: AppCofidurBundle:Category:edit}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_category_delete:
    path: /category/delete/{idCat}
    methods: [DELETE,GET]
    defaults: { _controller: AppCofidurBundle:Category:delete}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_category_up:
    path: /category/up/{idCat}
    methods: [POST,GET]
    defaults: { _controller: AppCofidurBundle:Category:up}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_category_down:
    path: /category/down/{idCat}
    methods: [POST,GET]
    defaults: { _controller: AppCofidurBundle:Category:down}
    requirements:
        methods: GET
        id: \d+

### page de taches
AppCofidurBundle_task_add:
    path: /task/add/{idCat}
    methods: [POST,GET]
    defaults: { _controller: AppCofidurBundle:Task:add}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_task_edit:
    path: /task/edit/{idTask}
    methods: [POST,GET]
    defaults: { _controller: AppCofidurBundle:Task:edit}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_task_delete:
    path: /task/delete/{idTask}
    methods: [DELETE,GET]
    defaults: { _controller: AppCofidurBundle:Task:delete}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_task_up:
    path: /task/up/{idTask}
    methods: [POST,GET]
    defaults: { _controller: AppCofidurBundle:Task:up}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_task_down:
    path: /task/down/{idTask}
    methods: [POST,GET]
    defaults: { _controller: AppCofidurBundle:Task:down}
    requirements:
        methods: GET
        id: \d+


### Pages de formation d'opérateurs ###
AppCofidurBundle_operatorformation_add:
    path: /operatorformation/add/
    methods: [POST,GET]
    defaults: { _controller: AppCofidurBundle:OperatorFormation:add}

AppCofidurBundle_operatorformation_edit:
    path: /operatorformation/edit/{idOpForm}
    methods: [POST,GET]
    defaults: { _controller: AppCofidurBundle:OperatorFormation:edit}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_operatorformation_delete:
    path: /operatorformation/delete/{idOpForm}
    methods: [DELETE,GET]
    defaults: { _controller: AppCofidurBundle:OperatorFormation:delete}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_operatorformation_show:
    path:  /operatorformation/show/{idOpForm}
    methods: [GET]
    defaults: { _controller: AppCofidurBundle:OperatorFormation:show }
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_operatorformation_show_all:
    path:  /operatorsformations/
    methods: [GET]
    defaults: { _controller: AppCofidurBundle:OperatorFormation:showAll }

#pages de operatorcategory
#routing plus forcement necessaire, cela dépend
#AppCofidurBundle_operatorcategory_add:
#    path: /operatorcategory/add/{idOpForm}/{idCategory}
#    defaults: { _controller: AppCofidurBundle:OperatorCategory:add}
#    requirements:
#        methods: GET
#        id: \d+

AppCofidurBundle_operatorcategory_edit:
    path: /operatorcategory/edit/{idOpForm}/{idCategory}
    methods: [POST,GET]
    defaults: { _controller: AppCofidurBundle:OperatorCategory:edit}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_operatorcategory_delete:
    path: /operatorcategory/delete/{idOpForm}/{idCategory}
    methods: [DELETE,GET]
    defaults: { _controller: AppCofidurBundle:OperatorCategory:delete}
    requirements:
        methods: GET
        id: \d+

#page de operatortasks
AppCofidurBundle_operatortask_add:
    path: /operatortask/add/{idOpForm}/{idCategory}/{idTask}
    methods: [POST,GET]
    defaults: { _controller: AppCofidurBundle:OperatorTask:add}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_operatortask_delete:
    path: /operatortask/delete/{idOpForm}/{idCategory}/{idTask}
    methods: [DELETE,GET]
    defaults: { _controller: AppCofidurBundle:OperatorTask:delete}
    requirements:
        methods: GET
        id: \d+
