services:
#    app_cofidur.example:
#        class: AppCofidurBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  app_cofidur.password_resetting:
      class: AppCofidurBundle\EventListener\PasswordResettingListener
      arguments: ['@router']
      tags:
          - { name: kernel.event_subscriber }
